export const BILLING_PLANS = {
  LIGHT: "LIGHT",
  PRO: "PRO",
} as const;

export const ONE_MONTH_MS = 30 * 24 * 3600 * 1000;

export const EMAIL_MESSAGE_TYPES = {
  SUBSCRIPTION_UPGRADED: "SUBSCRIPTION_UPGRADED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  LIMIT_REACHED_FREE: "LIMIT_REACHED_FREE",
  LIMIT_REACHED_PRO: "LIMIT_REACHED_PRO",
} as const;
